- chef/cookbooks/crowbar/files/default/config.ru
- chef/cookbooks/crowbar/templates/default/rainbows.cfg.erb
- crowbar_framework/config.ru
This fixes the performance issues caused by missing HTTP response headers.
Also included is a patch that reduces the app server workers startup time, effectively reducing the time-to-first-response.
> Fix performance issue w/ slow UI responses

- bin/crowbar_batch
These are changes from https://github.com/crowbar/barclamp-crowbar/pull/1171 that would still be valid after https://github.com/crowbar/barclamp-crowbar/pull/1181 is merged.
> Ruby 2.1 fixes for crowbar batch

- crowbar_framework/app/controllers/barclamp_controller.rb
NodeObject#allocated is undefined.
> Typo fix in allocated node filter (bnc#913696)

- crowbar_framework/app/assets/javascripts/jquery/ledUpdate.js
- crowbar_framework/app/controllers/nodes_controller.rb
- crowbar_framework/app/views/nodes/show.html.haml
This set of patches fixes https://bugzilla.suse.com/show_bug.cgi?id=912426
> Led update

- crowbar_framework/spec/controllers/crowbar_controller_spec.rb
Turn the two failing tests to skips for now.
The output will look like this:
Pending:
CrowbarController GET barclamp_index renders list of all barclamps
CrowbarController proposal updates PUT proposal_update validates a proposal from command line
> Make failing tests to skipped ones with FIXME

- crowbar_framework/app/models/crowbar_service.rb
Depends on crowbar/barclamp-crowbar#1175
> Exclude SLE12 platform.

- bin/crowbar_machines
- crowbar_framework/app/controllers/machines_controller.rb
- crowbar_framework/app/controllers/nodes_controller.rb
- crowbar_framework/app/models/node_object.rb
- crowbar_framework/app/views/nodes/_buttons_power.html.haml
- crowbar_framework/config/locales/crowbar/en.yml
- crowbar_framework/spec/controllers/machines_controller_spec.rb
- crowbar_framework/spec/controllers/nodes_controller_spec.rb
Note that the hard reboot/shutdown methods are not exposed in the UI.
> Use soft reboot/shutdown by default and provide hard reboot/shutdown actions

- crowbar_framework/app/controllers/barclamp_controller.rb
- crowbar_framework/app/models/node_object.rb
- crowbar_framework/spec/controllers/crowbar_controller_spec.rb
https://bugzilla.suse.com/show_bug.cgi?id=907440
> States validation

- bin/barclamp_lib.rb
- crowbar_framework/app/models/proposal_object.rb
I'm really tired so maybe my brain is missing something, but these look like obvious refactorings to some dumb code.
> Cleanup ProposalObject#status

- crowbar_framework/app/models/service_object.rb
This will select nodes for roles, based on constraints.
> Add select_nodes_for_role helper to help create default proposals

- crowbar_framework/app/models/service_object.rb
I guess this would have been found if we'd have test
coverage for this..
> Fix undefined variable exception

- crowbar_framework/doc/default/crowbar/batch.md
> documentation for crowbar batch

- crowbar_framework/app/helpers/application_helper.rb
- crowbar_framework/app/helpers/form_helper.rb
- crowbar_framework/app/models/node_object.rb
Depends on https://github.com/crowbar/barclamp-provisioner/pull/375
> Display not 100% available OS as disabled in dropdown menu

- chef/cookbooks/crowbar/recipes/default.rb
I'm not sure there is really a lot of use for
this right now here since crowbar-barclamp-crowbar should have
the right dependencies already, but I don't want to play
with that right now.
> Update package installation list here as well

- README.md
> Add code climate badge to the README

- crowbar_framework/app/models/node_object.rb
While checking if disks are already claimed, check first if the
current disk was already claimed and if so, use that key as unique_name
for further operations.
> Fix check for unclaimed disks (bnc#916442)

- crowbar_framework/app/controllers/support_controller.rb
- crowbar_framework/app/views/support/index.html.haml
- crowbar_framework/spec/controllers/support_controller_spec.rb
safe_html -> html_safe in support index view + tests.
> Typo fix in support

- crowbar_framework/app/models/node_object.rb
This is a backport of https://github.com/crowbar/barclamp-crowbar/pull/1164
> Backport fixes for waiting for chef-client on reinstalling a node

- crowbar_framework/app/models/service_object.rb
- crowbar_framework/spec/controllers/crowbar_controller_spec.rb
Needs testing, just checking if this is the correct approach.
cc: @vuntz @aspiers @tboerger
> [wip] Load proposal data from sqlite, instead via chef api

- crowbar_framework/app/models/node_object.rb
This supersedes https://github.com/crowbar/barclamp-crowbar/pull/1231
> Show asset tag if set on the node

- crowbar_framework/lib/remote_node.rb
RemoteNode uses puts as a default way of logging (since it assumes it
will be called from a forked process, where all file descriptors except
for stdout/in/err are closed).
However, it now needs to be used in another context, namely to check if
chef clients are running prior to applying of the role.
This patch adds an options hash to relevant methods and allows passing a
logger option. If not specified, it falls back to using puts.
cc @vuntz, @MaximilianMeister #1251
> Allow passing in logger as an option to RemoteNode methods

- crowbar_framework/.gitignore
> Add .ruby-version and coverage to .gitignore

- crowbar_framework/app/models/chef_object.rb
- crowbar_framework/app/models/node_object.rb
- crowbar_framework/app/models/service_object.rb
partially fixes bsc#857375
https://bugzilla.suse.com/show_bug.cgi?id=857375
https://trello.com/c/zj87VaeB
> apply_role: disable 15-minute chef run during apply_role

- crowbar_framework/app/models/chef_object.rb
- crowbar_framework/app/models/node_object.rb
- crowbar_framework/app/models/service_object.rb
https://github.com/crowbar/barclamp-crowbar/pull/1251
https://trello.com/c/zj87VaeB/196-3-p4-bnc-857375-disable-15-minutes-chef-client-run-during-proposal-application
> [stoney] Backport of #1251

- crowbar_framework/app/models/chef_object.rb
- crowbar_framework/app/models/node_object.rb
- crowbar_framework/app/models/service_object.rb
https://github.com/crowbar/barclamp-crowbar/pull/1251
https://trello.com/c/zj87VaeB/196-3-p4-bnc-857375-disable-15-minutes-chef-client-run-during-proposal-application
> [tex] Backport of #1251

- crowbar_framework/app/models/service_object.rb
Added comments that try to explain various bits & pieces of the deployment queue (queueing) and apply_role (deployment) algorithms we use.
Please add comments/questions/opinions.
*Do not merge*
cc: @vuntz @dirkmueller @aspiers
> [WIP] Decyphering deployment queue & apply_role

- crowbar_framework/lib/crowbar/validator/package_name_validator.rb
- crowbar_framework/spec/lib/crowbar/validator/package_name_validator_spec.rb
(cherry picked from commit b5d498f78755d5603bcc1a54f1aff9a8a4cf3298)
Backport of @thutterer PR https://github.com/crowbar/barclamp-crowbar/pull/1290
> add validation helper module

- chef/cookbooks/crowbar/recipes/default.rb
- crowbar_framework/app/models/node_object.rb
https://trello.com/c/ZnrdM70i/382-3-p10-make-reinstall-work-for-windows-nodes
> Fixing Reinstall, Power Off and Power Cycle for the windows nodes

- crowbar_framework/app/controllers/nodes_controller.rb
- crowbar_framework/spec/controllers/nodes_controller_spec.rb
> Handle /nodes/families json requests properly (bsc#926395)

- .rubocop_todo.yml
Additional to that I relaxed the AbcSize as this is currently far too much refactoring.
> Relax some rubocop rules like line length

- crowbar_framework/app/models/service_object.rb
Except for `elems` -> `roles` rename at https://github.com/crowbar/barclamp-crowbar/compare/master...bkutil:deployment_queue?expand=1#diff-0be8ea1f05c9441a59bb2b7ac65b1c62R1292 only adds documentation.
> Comment the deployment and queueing processes

- crowbar_framework/app/models/node_object.rb
- crowbar_framework/app/models/service_object.rb
This is based on work from @MaximilianMeister in https://github.com/crowbar/barclamp-crowbar/pull/1224
> Better handling for _remove roles

- crowbar_framework/Gemfile
- crowbar_framework/config/boot.rb
Also sync requirements between Gemfile and config/boot.rb
> Allow ohai 6.24.x

- crowbar_framework/app/models/service_object.rb
@vuntz This was forgotten. I just realized that now :)
@bkutil can you have a look if the code is fine? I haven't had the time to test it
> Proposals are no longer in a databag, but in a database now

- crowbar_framework/Gemfile
I have submitted the package to D:C:S:Rubygem as well
> add ruby debugger for development

- crowbar_framework/app/models/service_object.rb
Errors should not be silenced in service object and backtrace
should be always logged.
> Log errors backtraces

- crowbar_framework/config/crowbar.env
* Raised crowbar version
* Added initial rainbows worker
> Environment config updates

- chef/cookbooks/crowbar/files/default/crowbar.service
http://www.freedesktop.org/software/systemd/man/systemd.service.html#ExecStart=
> ExecStartPre requires an absolute path

- bin/barclamp_lib.rb
in the development environment you may want to use a different port
> eventually use CROWBAR_PORT from the environment

- crowbar_framework/lib/remote_node.rb
There's no reason to be so unhelpful with the log messages.
> log which host we're waiting for
