crowbar/barclamp-crowbar

chef/cookbooks/crowbar/templates/default/rainbows.cfg.erb

This reverts commit 93a7e299ba41e3c59d444eafe8371ac7fc89bac3.
Our deployment scripts assume that force-reload is in fact equivalent to
restart (i.e. reloads the code), which is not the case if we preload the
app.

Revert "Preload app code on rainbows startup"

---

chef/cookbooks/crowbar/recipes/default.rb

We use sprockets with uglifier, there is no point in installing
closure-compiler

Install uglifier, not closure-compiler

---

crowbar_framework/config/application.rb

This is breaking the JSON parsing for empty arrays, which we use with
the magic crowbar-deep-merge-template feature when creating the initial
crowbar proposal.
With deep munge enabled, we cannot remove the nagios proposal, which
results in failures when nagios barclamp is not available.
See:
https://github.com/rails/rails/issues/8832
https://github.com/rails/rails/issues/13420
We can revert this once switching to rails 5 (see comments in second
issue).

Do not use deep munge

---

crowbar_framework/lib/dsl/proposal/attribute.rb

The cinder backend UI uses a hack to workaround handlebars substituted
values and calls wrap_around. However, this is a method defined in form
helper. The helpers possibly might have been accessible from the DSL in rails 2,
but this is no longer the case in rails 4.

Include form helper

---

crowbar_framework/config/environments/development.rb
crowbar_framework/config/environments/production.rb
crowbar_framework/config/environments/test.rb

Rename the serve_static_assets to serve_static_files in the environment
configuration. This prevents
The configuration option `config.serve_static_assets` has been renamed
deprecation warnings (the option will be removed in rails 5).

Rename serve_static_assets to serve_static_files

---

crowbar_framework/lib/dsl/proposal/deployment.rb

I realized that my fix for https://github.com/crowbar/barclamp-crowbar/pull/1176 was incomplete - in fact, the same issue can happen in deployment.rb as well. This patch fixes that.

Followup on respond_to fix for DSL (PR#1176)

---

crowbar_framework/config/initializers/serializer.rb

This supersedes https://github.com/crowbar/barclamp-crowbar/pull/1171
Configure the ActiveModel::Serializers gem to not use root element in
the rendered JSON responses.
This keeps our API JSON responses consistent between cloud releases.

Disable root element in API JSONs (bnc#912309)

---

crowbar_framework/app/controllers/nodes_controller.rb

Selecting a non-default target platform for nodes in the bulk view didn't have
any effect if "allocate" was marked at the same time. Handling the target
platform attribute before the allocate attribute should fix the problem.

Fix changing the platform in bulk view

---

bin/crowbar

the crowbar CLI should only match crowbar binaries for his subcommands.
I stumbled upon this, when i had some files laying around on the admin node which were "accidentally" prefixed with `crowbar_`.
```bash
root@crowbar:~ # ls -l crowbar_*
-rw-r--r-- 1 root root  252 Jan 19 19:23 crowbar_batch.log
-rw-r--r-- 1 root root 5769 Jan 19 17:12 crowbar_batch_only_openstack.yml
root@crowbar:~ # crowbar help
Usage: crowbar <area> <subcommand>
Areas: batch batch.log batch_only_openstack.yml ceilometer ceph cinder crowbar database deployer dns glance heat ipmi keystone logging machines network neutron nfs_client node_state nova nova_dashboard ntp pacemaker provisioner rabbitmq reset reset_nodes reset_proposal suse_manager_client swift tempest trove updater
```
the two files in my working directory …

restrict available subcommands to only crowbar binaries

---

crowbar_framework/config/environments/development.rb
crowbar_framework/config/environments/production.rb
crowbar_framework/config/environments/test.rb
crowbar_framework/lib/crowbar/logger/formatter.rb

> The config.log_formatter setting does not have any effect on the
> actual log format, if TaggedLogger or AS::Logger is passed via config.logger.
> 
> This might be due to the way the TaggedLogger is initialized [1]. To
> make it work, we would have to first instantiate the logger, then set
> its formatter, then pass it to the tagged logging. This is ugly.
>
> We could also use ActiveSupport::Logger instead, but the
> config.log_formatter does not work there, either (unless we again set
> the formatter as an attribute).
As Thomas correctly pointed out, the config.log_format does not apply if the config.logger is set.
Let's just use simple logger for now, and add tagged logging later. Imho there is no fast and easy way how to keep both tagged logging and old log format (unless we …

Fix logging format (bnc#912805)

---

crowbar_framework/app/controllers/nodes_controller.rb

If a node is forgotten and then edited before it disappears, we get an
exception.
As the edit action is purely navigational (i.e. not called from an api),
redirect to the dashboard and displaying a flash notification should be
sufficient.

Go to dashboard on deleted node edit (bnc#913818)

---

crowbar_framework/Gemfile

This prevents
`named_routes.helpers` is deprecated, please use `route_defined?
deprecation warningis.

Update rspec rails to 3.1 compatible with rails 4

---

.travis.yml

Older versions won't work anymore since we broke compatibility.

Only run travis against Ruby 2.1

---

crowbar_framework/app/assets/javascripts/jquery/nodeList.js
crowbar_framework/app/assets/javascripts/misc/stringLocalize.js
crowbar_framework/app/helpers/nodes_helper.rb
crowbar_framework/app/models/service_object.rb
crowbar_framework/app/views/barclamp/_node_selector.html.haml
crowbar_framework/spec/models/service_object_spec.rb

* Add "platform" constraint:
"platform" => ['suse', /12.(0|1)/]
This will expect that the service have a platform equal to 'suse'
and a platform_version of 12.0 or 12.1
* Add "exclude_platform" constraint:
"exclude_platform" => [/suse/, '11.3']
If the platform is a SLES11 SP3, the service will not be installed.

Add two new validation constraints.

---

crowbar_framework/app/assets/javascripts/jquery/nodeList.js
crowbar_framework/app/models/service_object.rb
crowbar_framework/spec/models/service_object_spec.rb

In crowbar/barclamp-crowbar#1175 I introduced a wrong comparison
algorithm after missunderstanding how <=> works on Ruby.
This commit fix the issue and 8+ test cases to cover all operators.

Implement a proper comparison for versions.

---

crowbar_framework/app/models/node_object.rb
crowbar_framework/app/views/nodes/_buttons_power.html.haml

All actions that required ssh can't work for windows nodes since there's
no ssh server installed there.
Also add warning when trying to use API requiring ssh for windows nodes

Hide power actions UI for windows nodes

---

crowbar_framework/app/models/service_object.rb

This method is used to find out which node can be used for a specific
role, so using the platform constraints there makes sense.

Use new platform constraints for element_info method

---

chef/cookbooks/utils/libraries/helpers.rb

We have this code in a few barclamps, and it's not really understandable
at first. So the small helper will make it clearer what it's for, and
avoid copy & paste bugs.

Add CrowbarHelper.in_sledgehammer? helper

---

chef/cookbooks/apache2/templates/suse/mods/fastcgi.conf.erb

The deployed RadosGW configuration was not compatible with Apache 2.4,
which is to be used on SLE12.

Fix RadosGW on SLE12

---

chef/cookbooks/utils/providers/line.rb
chef/cookbooks/utils/recipes/default.rb
crowbar_framework/app/models/node_object.rb

Some (new) hardware is not supported by dmidecode, so the
dmi tree is missing in ohai. Just ignore it, since the
whole point of that is logging the information.

Treat DMI information as optional

---

bin/crowbar_reset

As we put this in bin now, being able to directly call it instead of
displaying some bug message helps.

Allow direct calls to crowbar_reset

---

crowbar_framework/app/controllers/barclamp_controller.rb

sledgehammer and crowbar_join need to be able to transition states to:
- problem: errors on boot
- reboot: on rebooting
- shutdown: on shutting down
- debug: special state for sledgehammer that can be triggered for
debugging

Add some states to list of valid transition states

---

crowbar_framework/app/models/node_object.rb
crowbar_framework/spec/models/node_object_spec.rb

A simple typo fix + test case.
!node.handle was always false, so the comparison with the new handle was
also false, and the dupe check error was never raised.
cc @tboerger @vuntz
https://bugzilla.suse.com/show_bug.cgi?id=915406

Fix uniq validation for node alias (bnc#915406)

---

crowbar_framework/app/controllers/nodes_controller.rb
crowbar_framework/config/locales/crowbar/en.yml

When bulk editing nodes, currently the default error message is
displayed, when the group contains invalid characters.
'Failed to save the nodes X.'
This patch adds correct handling of such case and the UI will
display a more informative message:
'The group should start ...'
cc @tboerger @vuntz

Display better error for invalid groups

---

crowbar_framework/app/models/service_object.rb
crowbar_framework/lib/platform_requirement.rb
crowbar_framework/lib/platform_version.rb
crowbar_framework/spec/lib/platform_requirement_spec.rb
crowbar_framework/spec/lib/platform_version_spec.rb

As the service object is already too bloated, this set of patches moves the node platform version checks into a separate classes.
It also simplifies the code a bit by not using lambdas, but having the methods as a part of (private) interface.
cc @aplanas

Refactor platform version requirements check

---

chef/cookbooks/utils/libraries/helpers.rb

We now have CrowbarPacemakerHelper.cluster_haproxy_vpublic_name, which
enables the operator to avoid using the generated hostnames.
(cherry picked from commit e29245b490e7188196f0fca18675c8030ea24277)

Use haproxy public name for public URL when using a cluster

---

crowbar_framework/app/models/node_object.rb

The code was totally broken, setting the result variable to a value that
is not something we want to return yet, and with some totally broken
code raising an exception (info = info.name = foo, where info.name just
doesn't exist)

Fix NodeObject.switch_find_info

---

crowbar_framework/lib/remote_node.rb

https://bugzilla.suse.com/show_bug.cgi?id=918270

Fix RemoteNode when hostname resolves to multiple addresses (bnc#918270)

---

crowbar_framework/app/models/node_object.rb

If chef-client is run on a node, but that node never went through the
discovered state, then crowbar never created the role for that node
(crowbar-$node).
This will result in failures when we list nodes because chef knows about
the node, and crowbar thinks it should know about it too.
Instead, if we see that the node role doesn't exist, then we pretend the
node just doesn't even exist.
https://bugzilla.suse.com/show_bug.cgi?id=900216

Totally ignore nodes that were never discovered by crowbar (bnc#900216)

---

crowbar_framework/app/models/node_object.rb

If there's no disk claimed (like on discovery of a node), then
node[:crowbar_wall][:claimed_disks] is nil (assuming node[:crowbar_wall]
exists, which is usually not the case).

Fix NodeObject.unique_name_already_claimed_by if no disk claimed

---

crowbar_framework/app/controllers/barclamp_controller.rb
crowbar_framework/spec/controllers/crowbar_controller_spec.rb

This action is not rendered in HTML, only as JSON when using the API.
Raise 404 when viewed as HTML, so rails will render it's standard
not-found page, as suggested in the BNC entry.
cc @vmoravec

Render 404 on barclamp_index in HTML (bnc#916221)

---

crowbar_framework/app/models/node_object.rb

This is just wrong: if we don't know the switch info, then let's not
pretend it's something else.
This fixes nodes appearing in different groups by default when there's
no switch info.
https://bugzilla.suse.com/show_bug.cgi?id=918785

Do not use node handle as fallback for switch name (bnc#918785)

---

crowbar_framework/app/models/node_object.rb

When checking if a disk is already claimed, all links to the claimed
disks are checked as well. Allow the case where the real device name is
given as possible linkname. This can happen when using virtual hardware
where the devicename might be "/dev/vda".
Related to bnc#919469

Handle case where device name is linkname

---

crowbar_framework/app/models/node_object.rb

Commit 2ad06ccf3f89e36697581621418dc3f545277679 was wrong. The "device"
parameter given to link_to_device?() is for instance "vda" (without a
trailing "/dev"). But the linkname is the full path in the case where
linkname is the device name.

Fix linkname check

---

crowbar_framework/app/models/node_object.rb

Bug https://bugzilla.suse.com/show_bug.cgi?id=919469
This is fix when virtio disk and the target platform is one that might not have the "by-path" links (e.g. SLES 12). Avoid using "by-path".
This can occur for `{"/dev/vda"=>{"owner"=>"Boot"}}`

Fix for link_to_device on SLE12 for virtio disks, (bnc#919469)

---

crowbar_framework/app/assets/javascripts/jquery/hideShowClusterConf.js

We were counting the same cluster twice: once by looking at the
attributes, and once due to the nodeListNodeAllocated event that happens
on page load.

Fix hideShowClusterConf.js when a cluster is assigned to role on load

---

crowbar_framework/app/models/node_object.rb

The node dashboard relies on the fact that group_order is different for
each node. This was not the case when two nodes are actually VMWare VMs
that are ultimately plugged in the same switch.
So instead of only relying on the information of where the node is
plugged on the switch, also append to that the alias of the node to
ensure group_order is unique.

Make NodeObject.group_order return a unique value

---

crowbar_framework/app/models/node_object.rb

The node dashboard relies on the fact that group_order is different for
each node. This was not the case when two nodes are actually VMWare VMs
that are ultimately plugged in the same switch.
So instead of only relying on the information of where the node is
plugged on the switch, also append to that the alias of the node to
ensure group_order is unique.
(cherry picked from commit f40c7404030ea069f64bca4186b33a04cf5bb2c9)

[backport] Make NodeObject.group_order return a unique value

---

crowbar_framework/index/index.html

As discussed [here](https://github.com/SUSE-Cloud/barclamp-crowbar/pull/18) we don't need the collapse menu as we only have a single link in the right navbar menu and don't want to depend on more CDN content.

remove broken collapse menu on port 80 page

---

crowbar_framework/app/models/chef_object.rb
crowbar_framework/app/models/proposal.rb
crowbar_framework/app/models/proposal_object.rb
crowbar_framework/app/models/service_object.rb
crowbar_framework/db/migrate/20150312081459_create_proposals.rb
crowbar_framework/db/schema.rb
crowbar_framework/lib/crowbar/proposal_methods.rb
crowbar_framework/spec/fixtures/offline_chef/data_bag_item_crowbar-bc-template-crowbar.json
crowbar_framework/spec/models/proposal_object_spec.rb
crowbar_framework/spec/models/proposal_spec.rb

This is a wip branch attempting to move proposals out of couch db into sqlite.
cc: @vuntz @tboerger @aspiers
Re-creating the pull request against a feature branch as this is not mergeable into master ATM.
The idea behind this is to create a `ProposalObject`-compatible replacement, then keep it in sync by adding hooks into `ProposalObject` `save` and `destroy` methods.
Bi-directional sync is still WIP, but it'd allow us to gradually replace the old `ProposalObject`, instead of making the switch in one step.
To reduce duplication, all common methods are refactored out into `ProposalMethods` module, then included into both classes. The rest is implemented by each class separately.
The API compatibility is tested using rspec, by checking that  both objects respond to the same set of public …

[WIP] feature/sqlite storage

---

crowbar_framework/index/index.html

As @nkrinner suggested in [Bugzilla](https://bugzilla.suse.com/show_bug.cgi?id=922699) the panel-heading text could be a link to port 3000 as well.
This needs minor changes in the page's JavaScript.
Besides that, I found two other small issues:
- The top-left logo is a link to "/" which does nothing but lead to the same error page the user is already on. So shouldn't we change that to a link to port 3000 too?
- The JavaScript adds ":3000" to the current location which is fine when you reached that site directly via port 80. But if you work with port-forwarding like in our virtual cloud setups, the link then becomes something like "hardware:1180:3000" which is not valid nor working. Shouldn't we improve the script to remove the trailing ":\d*" first and then add the ":3000" ? …

add and adjust links on port 80 page

---

crowbar_framework/app/models/proposal.rb
crowbar_framework/app/models/proposal_object.rb
crowbar_framework/lib/crowbar/proposal_methods.rb
crowbar_framework/spec/models/proposal_object_spec.rb
crowbar_framework/spec/models/proposal_spec.rb

This enables almost seamless replacement of ProposalObject and Proposal,
as the changes will be mirrored into the other model transparently.
The changes can be dropped after we're done migrating barclamps.

Bidirectional sync for models

---

crowbar_framework/app/controllers/barclamp_controller.rb
crowbar_framework/app/controllers/dashboard_controller.rb
crowbar_framework/app/controllers/deploy_queue_controller.rb
crowbar_framework/app/controllers/support_controller.rb
crowbar_framework/app/helpers/nodes_helper.rb
crowbar_framework/app/helpers/proposals_helper.rb
crowbar_framework/app/models/chef_object.rb
crowbar_framework/app/models/crowbar_service.rb
crowbar_framework/app/models/proposal.rb
crowbar_framework/app/models/role_object.rb
crowbar_framework/app/models/service_object.rb
crowbar_framework/lib/utils.rb
crowbar_framework/lib/utils/json_with_indifferent_access.rb
crowbar_framework/spec/controllers/crowbar_controller_spec.rb
crowbar_framework/spec/controllers/nodes_controller_spec.rb
crowbar_framework/spec/models/chef_object_spec.rb
crowbar_framework/spec/spec_helper.rb

This patchset replaces most of the calls to ProposalObject with calls to Proposal in the crowbar barclamp.
What has not been replaced and is still backed by databags:
* The deployment queue
* Network configuration

[wip] Replace calls to ProposalObject with Proposal

---

chef/cookbooks/utils/libraries/helpers.rb

This is the exact same thing we're doing for the public IP address/DNS
name.
The reason it's needed is for keystone admin API which are being done
through the admin endpoint. As this is a rather minimal use case, we do
not expose the setting in the UI for the nodes -- which means the node
would have to be edited directly.
https://bugzilla.suse.com/show_bug.cgi?id=927469
Depends on https://github.com/crowbar/barclamp-pacemaker/pull/190

Use admin name attribute when computing host for admin URL (bsc#927469)

---

chef/cookbooks/utils/libraries/helpers.rb

**Backport of https://github.com/crowbar/barclamp-crowbar/pull/1263 to tex**
This is the exact same thing we're doing for the public IP address/DNS
name.
The reason it's needed is for keystone admin API which are being done
through the admin endpoint. As this is a rather minimal use case, we do
not expose the setting in the UI for the nodes -- which means the node
would have to be edited directly.
https://bugzilla.suse.com/show_bug.cgi?id=927469
(cherry picked from commit 89628b8672a14200c52c7f274f3c8b318258d4c1)

[tex] Use admin name attribute when computing host for admin URL (bsc#927469)

---

crowbar_framework/config/initializers/sqlite_transaction_monkey_patch.rb

With deferred transaction mode, used by ActiveRecord by default, we were
getting SQLite3::BusyException when two processess attempted to do an update to
IPMI proposal at the same time. Using immediate transaction mode
(https://www.sqlite.org/lang_transaction.html) prevents two threads/processess
to begin an (immediate) transaction simultaneously and seems to alleviate the
issue.
refs https://github.com/crowbar/barclamp-crowbar/pull/1269

Use immediate transaction mode in SQLite

---

chef/cookbooks/apache2/templates/default/apache2.conf.erb
chef/cookbooks/apache2/templates/default/default-site.erb
chef/cookbooks/apache2/templates/default/mods/alias.conf.erb
chef/cookbooks/apache2/templates/default/mods/proxy.conf.erb
chef/cookbooks/apache2/templates/default/mods/status.conf.erb
chef/cookbooks/apache2/templates/default/ports.conf.erb
chef/cookbooks/apache2/templates/default/web_app.conf.erb
chef/cookbooks/apache2/templates/suse/mods/status.conf.erb

Note that NameVirtualHost is gone now: this is automatically detected.

Fix apache config file to work with apache 2.4 or later

---

crowbar_framework/app/controllers/deploy_queue_controller.rb
crowbar_framework/app/models/proposal.rb
crowbar_framework/app/models/proposal_object.rb
crowbar_framework/app/models/service_object.rb
crowbar_framework/lib/schema_migration.rb

This patch replaces the remaining uses of ProposalObject with either Proposal calls, or, where none of the Proposal API methods are required (as e.g. for the deployment queue), uses Chef::DataBag class directly.
This will allow for dropping the ProposalObject related code now, then move away from data bags towards a separate table/database later.
There are similar pull requests for other barclamps, they'll be referenced below.
I noticed a slight problem with this and referencing PRs - ProposalObject rescues any error raised by Chef::DataBag.load - this'll have to be fixed...

Replace remaining ProposalObject calls with Chef::DataBag

---

crowbar_framework/doc/default/crowbar/batch.md

The @ and ` characters can be used anywhere in a plain string except at the beginning, because they are reserved indicators:
http://yaml.org/spec/1.2/spec.html#id2774228
See https://bugzilla.suse.com/show_bug.cgi?id=932619 for the corresponding change in product documentation.

document YAML requirement to quote alias strings

---

crowbar_framework/app/models/service_object.rb

If a node is on multiple roles for this proposal, then we only want to
have chef-client stopped/started once for this node.

On apply_role, do not stop/start chef several times for nodes

---

chef/cookbooks/utils/libraries/search.rb

Check if node[barclamp][:config] exist to prevent
undefined method `[]' for nil:NilClass
It was reported in https://bugzilla.suse.com/show_bug.cgi?id=934227

Fix for search_env_filtered(), (bnc#934227)

---

chef/cookbooks/utils/libraries/search.rb

Check if node[barclamp][:config] exist to prevent
undefined method `[]' for nil:NilClass
(cherry picked from commit 763ff24)
This is needed if want to merge https://github.com/crowbar/barclamp-neutron/pull/223

[tex] Fix for search_env_filtered(), (bnc#934227)

---

crowbar_framework/lib/crowbar/validator/package_name_validator.rb
crowbar_framework/spec/lib/crowbar/validator/package_name_validator_spec.rb

After some discussion in crowbar/barclamp-provisioner#427 @aspiers suggested it would be best to have a module for validations like the RegEx from mentioned Pull Request.
This way it's easy to write tests for these validations.
This PR adds such a module, a method for package name validation and its test.

Add validation module with method for package name checking

---

crowbar_framework/Gemfile

To ensure that development and production environments are
somewhat compareable os that the added rspec tests have an
actual meaning, the dependencies are locked on the 3rd level
of the semantic versioning.

Fix various dependencies to be closer to production

---

.hound.yml
.rubocop.yml

This configs are needed to run HoundCI Style tests for our PRs. The
rubocop config is a adaption from the default config.
https://raw.githubusercontent.com/thoughtbot/hound/master/config/style_guides/ruby.yml

Introduce HoundCI

---

crowbar_framework/config/branding.yml
crowbar_framework/index/index.html
crowbar_framework/public/404.html
crowbar_framework/public/422.html
crowbar_framework/public/500.html

The default crowbar should be provider neutral as possible. So let's
move the standard to the crowbar website.

Update "Provided by" text and links

---

crowbar_framework/app/models/node_object.rb

In some setups on SLES12 there are no /dev/disk-by*/ links at all for virtio
disks. Return /dev/vdX as the unique name immediately in such cases.

Fix 'unique_device_for()' for SLES12 virtio devices (bsc#936712)

---

crowbar_framework/app/models/node_object.rb

In some setups on SLES12 there are no /dev/disk-by*/ links at all for virtio
disks. Return /dev/vdX as the unique name immediately in such cases.
(cherry picked from commit f697321555a05a1a78b6100564e4aa9e81e653c6)
It was code-reviewed in https://github.com/crowbar/barclamp-crowbar/pull/1297

[tex] Fix 'unique_device_for()' for SLES12 virtio devices (bsc#936712)

---

crowbar_framework/lib/barclamp_catalog.rb

`barclamps[barclamp]` is not always available (e.g. `barclamp-deployer`) in this
case we also want the barclamp name.

Fix display_name when barclamps[barclamp] doesn't exists (bsc#935233)

---

crowbar_framework/app/controllers/nodes_controller.rb
crowbar_framework/spec/controllers/nodes_controller_spec.rb

We do not handle json request for this page. Let's return a prober error
code instead of run in a "internal server error".
(cherry picked from commit 17734a7ef8a46738b8d61ced92d2517187bb80e4)

[tex] Handle /nodes/families json requests properly (bsc#926395)

---

crowbar_framework/lib/barclamp_catalog.rb

It can happen that a barclamp has no catalog entry (e.g. failed
installation). To prefent UI crashes use the barclamp name but log this
as a warning.
https://bugzilla.suse.com/show_bug.cgi?id=935233
(cherry picked from commit ec6053ea6afc00a2bab7db062604b182c8d161e4)

[tex] Fix display_name when barclamps[barclamp] doesn't exists (bsc#935233)

---

crowbar_framework/app/models/service_object.rb

For windows nodes, we rely on the regular chef-client run and we don't
connect through ssh.
http://bugzilla.suse.com/show_bug.cgi?id=937760

Do not try to stop/start chef-client daemon on windows nodes

---

crowbar_framework/lib/crowbar/product.rb

Previously this would just check if suse_enterprise_storage was in the
BarclampCatalog.  Unfortunately, this will always be true if the Ceph
barclamp is installed, as it's a member of suse_enterprise_storage since:
https://github.com/crowbar/barclamp-ceph/pull/154
See subsequent discussion at:
https://github.com/crowbar/barclamp-crowbar/pull/1266
This fix tightents up the check to verify that suse_enterprise_storage
is a member of itself, which won't happen unless that barclamp is
really, truly installed.
Signed-off-by: Tim Serong <tserong@suse.com>

Tighten up Crowbar::Product::is_ses? check

---

crowbar_framework/config/locales/crowbar/en.yml

translation missing: en.barclamp.show_index.blockui_message

i18n: fix missing translation in vanilla crowbar

---

crowbar_framework/app/controllers/nodes_controller.rb

If you try to set an alias or public_name on an unallocated node in bulk
edit, and you try to allocate it at the same time crowbar ignores the
alias and public_name you defined. Because of that i have moved the
alias and public_name assignment below the allocation, that way this
information doesn't get lost.
https://bugzilla.suse.com/show_bug.cgi?id=918523

Fix alias in bulk edit (bnc#918523)

---

crowbar_framework/app/models/node_object.rb

It turns out that there is an attribute for defining the default
platform, and therefore we should not just rely on the OS of the admin
server.
This also means that the variable cannot be cached forever since the
attribute might change.

Use default_os attribute from provisioner as default platform

---

chef/cookbooks/apache2/recipes/mod_ssl.rb
chef/cookbooks/apache2/templates/suse/mods/ssl.conf.erb

Apache 2.4 doesn't understand the SSLMutex directive, so without this
fix SSL radosgw (or SSL anything else) on Apache 2.4 on SLE 12 won't
work.
Signed-off-by: Tim Serong <tserong@suse.com>

Update ssl.conf.erb for Apache 2.4 on SLE 12 (bsc#935050)

---

bin/crowbar_batch

`@` is a reserved indicator in YAML and can't start a plain scalar:
http://yaml.org/spec/1.2/spec.html#id2774228
Therefore aliases need to be wrapped in double-quotes.  This was already fixed in the documentation for `crowbar batch build`:
https://github.com/crowbar/barclamp-crowbar/pull/1278
but it appears that I deliberately made `batch export` strip the quotes in the original implementation (presumably on grounds of ugliness) before realising that that violated the YAML spec.

batch export: don't strip double-quotes from aliases

---

chef/cookbooks/crowbar/recipes/default.rb

It just needs to point to /usr/sbin/service.

Also create rccrowbar symlink on SLE12

---

bin/crowbar_batch

- abort with a better error message if the exported YAML file contains aliases that are unknown to Crowbar
- abort if the YAML file is empy (bugfix)
- replace a warn&exit two-liner with a simple abort

crowbar_batch build: improve YAML file error handling

---

crowbar_framework/app/models/service_object.rb

Currently this causes a massive slowdown of proposal apply
up to a point where a HA deployment is no longer possible.
Revert until a proper fix is being found.
This reverts commit 41b6bca7f9e260a398df536015f22cca4c6c3f26.

Revert "apply_role: disable 15-minute chef run during apply_role"

---

chef/cookbooks/apache2/recipes/default.rb

On both SLE11 and SLE12, the package name is `apache2`.  Usually installing `httpd` works because the `apache2` package provides the `httpd` virtual package; however if there is a `SLE12-HA-Pool` repository available then `lighttpd` could accidentally get installed instead.
Unfortunately this missed Milestone 2 and appears to break Horizon when HA is used.  Tested on c19 and it works.

ensure we install apache2 not lighttpd

---

chef/cookbooks/crowbar/recipes/default.rb
crowbar_framework/Gemfile
crowbar_framework/config/boot.rb

* this is primarily needed to provide a rake task (db:data:dump)
for the supportutils-plugin-suse-openstack-cloud but is also useful
in general, as you can dump the crowbar database without having to
specify the type of database (SQLite, MySQL, PostgreSQL etc...)

add yaml_db to the list of gems
